import {
  SiSpringboot,
  SiSpringsecurity,
  SiSpring,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiApachekafka,
  SiDocker,
  SiKubernetes,
  SiGithubactions,
  SiReact,
  SiTailwindcss,
  SiAmazonapigateway,
  SiHibernate,
} from "react-icons/si";
import { DiJava, DiRedis } from "react-icons/di";

export const skills = [
  { Icon: DiJava, name: "Java" },
  { Icon: SiSpringboot, name: "Spring Boot" },
  { Icon: SiSpringsecurity, name: "Spring Security" },
  { Icon: SiSpring, name: "Spring Cloud" },
  { Icon: SiAmazonapigateway, name: "API Gateway" },
  { Icon: SiHibernate, name: "Hibernate / JPA" },
  { Icon: SiMysql, name: "MySQL" },
  { Icon: SiPostgresql, name: "PostgreSQL" },
  { Icon: SiMongodb, name: "MongoDB" },
  { Icon: DiRedis, name: "Redis" },
  { Icon: SiApachekafka, name: "Apache Kafka" },
  { Icon: SiDocker, name: "Docker" },
  { Icon: SiKubernetes, name: "Kubernetes" },
  { Icon: SiGithubactions, name: "GitHub Actions" },
  { Icon: SiReact, name: "React.js" },
  { Icon: SiTailwindcss, name: "Tailwind CSS" },
];
